PLUS = '+'
MINUS = '-'
MULT = '*'
DIV = '/'
OPEN_PARENT = '('
CLOSE_PARENT = ')'

INT = 'int'
OPERATOR = 'operator'

OPEN_COMMENT = '/*'
CLOSE_COMMENT = '*/'

STD_FILE_NAME = '../examples/example.c'

SIGN_OPS = (PLUS, MINUS)
TERM_OPS = (MULT, DIV)
EXPR_OPS = (PLUS, MINUS)
FACT_OPS = (OPEN_PARENT, CLOSE_PARENT)

BINOP_CHILD_SIZE = 2
UNOP_CHILD_SIZE = 1
INTVAL_CHILD_SIZE = 0
NOOP_CHILD_SIZE = 0

