PLUS = '+'
MINUS = '-'
MULT = '*'
DIV = '/'
ASSIGN = '='
SEMICOLON = ';'
UNDERSCORE = '_'

INT = 'int'
OPERATOR = 'operator'
PRINT = 'printf'
RESERVED_WORD = 'reserved_word'
VARIABLE = 'variable'

OPEN_PARENT = '('
CLOSE_PARENT = ')'
OPEN_BLOCK = '{'
CLOSE_BLOCK = '}'
OPEN_COMMENT = '/*'
CLOSE_COMMENT = '*/'

STD_FILE_NAME = '../examples/example.c'

SIGN_OPS = (PLUS, MINUS)
TERM_OPS = (MULT, DIV)
EXPR_OPS = (PLUS, MINUS)
FACT_OPS = (OPEN_PARENT, CLOSE_PARENT)
RESERVED_WORDS = (PRINT)

BINOP_CHILD_SIZE = 2
UNOP_CHILD_SIZE = 1
INTVAL_CHILD_SIZE = 0
VARVAL_CHILD_SIZE = 0
NOOP_CHILD_SIZE = 0

