PLUS = '+'
MINUS = '-'
MULT = '*'
DIV = '/'
ASSIGN = '='
SEMICOLON = ';'
UNDERSCORE = '_'
EQUALS = '=='
LT = '<'
GT = '>'
AND = '&&'
OR = '||'
NOT = '!'

IF = 'if'
ELSE = 'else'
WHILE = 'while'
INT = 'int'
OPERATOR = 'operator'
PRINT = 'printf'
SCANF = 'scanf'
RESERVED_WORD = 'reserved_word'
VARIABLE = 'variable'

OPEN_PARENT = '('
CLOSE_PARENT = ')'
OPEN_BLOCK = '{'
CLOSE_BLOCK = '}'
OPEN_COMMENT = '/*'
CLOSE_COMMENT = '*/'

STD_FILE_NAME = '../examples/example.c'

SIGN_OPS = (PLUS, MINUS)
TERM_OPS = (MULT, DIV)
EXPR_OPS = (PLUS, MINUS)
FACT_OPS = (OPEN_PARENT, CLOSE_PARENT)
RESERVED_WORDS = (PRINT, IF, ELSE, WHILE, SCANF)
LOGIC_EXPR_OPS = (EQUALS, LT, GT)

TRIOP_CHILD_SIZE = 3
BINOP_CHILD_SIZE = 2
UNOP_CHILD_SIZE = 1
INTVAL_CHILD_SIZE = 0
VARVAL_CHILD_SIZE = 0
NOOP_CHILD_SIZE = 0
SCANF_CHILD_SIZE = 0
